# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161226_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
