# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
