# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20161215_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
