# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_newproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='newproject',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.CharField(blank=True, default=1, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
