# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-31 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161227_0053'),
        ('accounts', '0002_auto_20161221_1904'),
    ]

    operations = [
    ]
